repos:
  - repo: local
    hooks:
      - id: format-includes
        name: format includes
        entry: python tools/format_includes.py
        language: system
        files: ^src/.*\.(hpp|cpp)$
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.7
    hooks:
      - id: clang-format
  - repo: https://github.com/BlankSpruce/gersemi
    rev: 0.24.0
    hooks:
      - id: gersemi
